name: front
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  talker_flutter: ^4.9.3
  talker_dio_logger: ^4.9.3
  talker_bloc_logger: ^4.9.3

  flutter_bloc: ^9.1.1

  get_it: ^8.2.0
  injectable: ^2.5.1
  go_router: ^16.1.0
  freezed_annotation: ^3.1.0
  dio: ^5.9.0
  retrofit: ^4.7.1
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_verify: ^3.1.1
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0
  go_router_builder: ^3.0.1
  injectable_generator: ^2.7.0
  freezed: ^3.0.6
  retrofit_generator: ^9.6.0
  json_serializable: ^6.9.5

flutter:
  assets:
    - images/

  uses-material-design: true
